server:
  port: 9099
#  servlet:
#    context-path: /app
#logging:
#  level:
#    root: debug
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/market
    username: w0id
    password: 2311
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: create